# Generated by Django 5.2.6 on 2025-09-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('dob', models.DateTimeField()),
                ('gender', models.CharField(max_length=55)),
                ('locality', models.CharField(max_length=55)),
                ('city', models.CharField(max_length=55)),
                ('pin', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chattogram', 'Chattogram'), ('Khulna', 'Khulna'), ('Rajshahi', 'Rajshahi'), ('Barishal', 'Barishal'), ('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur'), ('Mymensingh', 'Mymensingh')], max_length=55)),
                ('mobile', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('job_city', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chattogram', 'Chattogram'), ('Khulna', 'Khulna'), ('Rajshahi', 'Rajshahi'), ('Sylhet', 'Sylhet')], max_length=55)),
                ('profile_image', models.ImageField(blank=True, upload_to='proimg')),
                ('my_file', models.ImageField(blank=True, upload_to='docs')),
            ],
        ),
    ]
